version: "3.8"

services:
    traefik:
        image: "traefik:v2.7"
        container_name: "traefik"
        restart: "unless-stopped"
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./traefik.yml:/etc/traefik/traefik.yml:ro"
            - "./ssl_conf.yml:/etc/traefik/ssl_conf.yml"
            - "./certs:/etc/traefik/certs"
        networks:
            - traefik

networks:
    traefik:
        external: true
