## Static configuration
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

# Docker configuration backend
providers:
  docker:
    network: traefik
    exposedByDefault: false
    watch: true
  file:
    filename: /etc/traefik/ssl_conf.yml
    watch: true

# API and dashboard configuration
api:
  insecure: true
  debug: true
  dashboard: true

log:
  level: debug
